### PR TITLE
Add disabled for option

### PR DESCRIPTION
**Pull request by s-pyadyshev**
Add disabled code adn style for option tags as well.

### CODE REVIEW

**Comment by mdbassit** [comment]
Hello,

 Thank you for your contribution, but I actually already implemented this in a version that I haven't published yet. I will release it soon.

**Comment by gebederry** [comment]
@mdbassit Please release the new version.

**Comment by mdbassit** [comment]
@gebederry My implementation is flawed and only works for certain cases, which is enough for my own use, but it's not good enough to release to the public. I will work on it some more when I have time.

Please create a new issue (feature request) to ask for this.

**Comment by gebederry** [comment]
@mdbassit I see, thanks for your work!

**Comment by mdbassit** [comment]
I just implemented this feature.

**Pull request closed without merging**
